### ISSUE TITLE
State of the plugin? Pairing Errors.

### ISSUE THREAD

**Issue by rcoletti116** [quiqueck/homebridge-homekit-proxy#1]
Just trying to find out the state of your plugin. It's a great concept and I see posts requesting similar functionality regularly! Thanks for the time in making this.

I've installed and tried it out. Discovery seems to work but the pairing fails on all devices with the same error:

```
(node:11449) UnhandledPromiseRejectionWarning: Error: M2: Error: 6
    at PairingProtocol.parsePairSetupM2 (/usr/local/lib/node_modules/homebridge-homekit-proxy/node_modules/hap-controller/lib/protocol/pairing-protocol.js:173:19)
    at HttpClient.startPairing (/usr/local/lib/node_modules/homebridge-homekit-proxy/node_modules/hap-controller/lib/transport/ip/http-client.js:64:37)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async HttpClient.pairSetup (/usr/local/lib/node_modules/homebridge-homekit-proxy/node_modules/hap-controller/lib/transport/ip/http-client.js:102:34)
    at async /usr/local/lib/node_modules/homebridge-homekit-proxy/cli.js:134:17
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11449) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:11449) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by PetrKadlecCS** [comment]
Hello,
I have the same issue:

> Enter PIN for VOCOlinc-FLB-179912 (XXX-XX-XXX or XXXX-XXXX or XXXXXXXX): 996-14-325
> Pin: 996-14-325
> (node:12658) UnhandledPromiseRejectionWarning: Error: M2: Error: 6
>     at PairingProtocol.parsePairSetupM2 (/usr/local/lib/node_modules/homebridge-homekit-proxy/node_modules/hap-controller/lib/protocol/pairing-protocol.js:173:19)
>     at HttpClient.startPairing (/usr/local/lib/node_modules/homebridge-homekit-proxy/node_modules/hap-controller/lib/transport/ip/http-client.js:64:37)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
>     at async HttpClient.pairSetup (/usr/local/lib/node_modules/homebridge-homekit-proxy/node_modules/hap-controller/lib/transport/ip/http-client.js:102:34)
>     at async /usr/local/lib/node_modules/homebridge-homekit-proxy/cli.js:134:17
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:12658) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> (node:12658) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Tested on Raspberry Pi 2B, Homebridge v1.3.5, Node.js v14.18.1, Npm v6.14.15.

I am ready for further tests if necessary ;).

**Comment by b2un0** [comment]
got the same error but fixed it.

**the device must be unpaired from your Home!**

1. add the device with Homekit (in my case, a `Xiaomi Mi Smart Bedside Lamp 2 `)
2. the device is added to Home and WiFi
3. remove device from Home
4. device i still in WiFi
5. now scan mit `homekitPair` and enter the pin
6. you got the json file as explained
