### ISSUE TITLE
Error: EAFNOSUPPORT, Address family not supported by protocol

### ISSUE THREAD

**Issue by snwfdhmp** [quiqueck/homebridge-homekit-proxy#5]
Hey, I'm getting an error with your program as well as the original repository by MartinPham.

It says that the address family is not supported by protocol. I assumed it was due to ipv6 but I tried disabling it with `net.ipv6.conf.all.disable_ipv6 = 1` in sysctl.conf but as you can see below it's not fixing anything.

```
root@homebridge-vm:/var/lib/homebridge $ ifconfig
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:91:92:49:2f  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.1.0.34  netmask 255.255.255.0  broadcast 10.1.0.255
        ether 00:15:5d:00:66:00  txqueuelen 1000  (Ethernet)
        RX packets 74439  bytes 24435769 (24.4 MB)
        RX errors 0  dropped 234  overruns 0  frame 0
        TX packets 5975  bytes 1856188 (1.8 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 140  bytes 21998 (21.9 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 140  bytes 21998 (21.9 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

root@homebridge-vm:/var/lib/homebridge $ homekitPair -i eth0
/opt/homebridge/lib/node_modules/homebridge-homekit-proxy/node_modules/@abandonware/noble/lib/hci-socket/hci.js:80
  this._socket = new BluetoothHciSocket();
                 ^

Error: EAFNOSUPPORT, Address family not supported by protocol
    at new Hci (/opt/homebridge/lib/node_modules/homebridge-homekit-proxy/node_modules/@abandonware/noble/lib/hci-socket/hci.js:80:18)
    at new NobleBindings (/opt/homebridge/lib/node_modules/homebridge-homekit-proxy/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:25:15)
    at module.exports (/opt/homebridge/lib/node_modules/homebridge-homekit-proxy/node_modules/@abandonware/noble/lib/resolve-bindings.js:13:12)
    at Object.<anonymous> (/opt/homebridge/lib/node_modules/homebridge-homekit-proxy/node_modules/@abandonware/noble/index.js:2:51)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  errno: 97,
  code: 'EAFNOSUPPORT',
  syscall: 'socket'
}
```

**Comment by NicksonYap** [comment]
This project seems to require Bluetooth, I was using Synology and I think a Raspberry Pi is more properly supported
Ref: 
https://github.com/dgreif/homebridge-hatch-baby-rest/issues/25
