### ISSUE TITLE
Error: M4: Error: 2

### ISSUE THREAD

**Issue by MattB1981** [quiqueck/homebridge-homekit-proxy#6]
Can command as just homekit pair
I found and selected my device, it's already removed from homekit and I get the below error readout. Any ideas? 

/usr/lib/node_modules/homebridge-homekit-proxy/node_modules/hap-controller/lib/protocol/pairing-protocol.js:222
            throw new Error(`M4: Error: ${tlv.get(Types.kTLVType_Error).readUInt8(0)}`);
                  ^

Error: M4: Error: 2
    at PairingProtocol.parsePairSetupM4 (/usr/lib/node_modules/homebridge-homekit-proxy/node_modules/hap-controller/lib/protocol/pairing-protocol.js:222:19)
    at HttpClient.finishPairing (/usr/lib/node_modules/homebridge-homekit-proxy/node_modules/hap-controller/lib/transport/ip/http-client.js:87:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HttpClient.pairSetup (/usr/lib/node_modules/homebridge-homekit-proxy/node_modules/hap-controller/lib/transport/ip/http-client.js:102:9)
    at async /usr/lib/node_modules/homebridge-homekit-proxy/cli.js:134:17

**Comment by MattB1981** [comment]
This is trying to pair a Yee bedside lamp but I get it with everything I've tried so far

**Comment by MattB1981** [comment]
I have lan control turned on now and same results.
